### PR TITLE
DJB-1 Initializes repository with metafiles and current state of DDF JAXB modules

### PR DESCRIPTION
**Pull request by coyotesqrl**
Fixes: #1

### CODE REVIEW

**Review by paouelle — APPROVED** [review]

**Review by clockard — APPROVED** [review]
Going to rely on a CI build for finding issues with this pr.

**Review by blen-desta — APPROVED** [review]

**Review by brjeter — COMMENTED** [review]
❓ Does it not make sense to have this repo use `ddf-parent` as the parent module?

**Comment by coyotesqrl** [comment]
@brjeter I contemplated using `ddf-parent` but decided that in the long run it would be easier for this repository to manage the small number of dependencies independently. When the next two phases of this are worked - firstly, consolidating to a single set of plugins and versions for all the artifacts and then secondly, updating so it will better work with J11 - it'll be much easier to manage a small set of version properties or `dependencyManagement` and `pluginManagement` entries in the reactor pom.

**Review by bakejeyner — APPROVED** [review]

**Comment by coyotesqrl** [comment]
@clockard Working on getting CI setup. Should be available, hopefully by early next week.

In the interim, I'm trying to find someone to manually hero this with the associated DDF PR - codice/ddf#3898

**Review by brjeter — APPROVED** [review]

**Comment by coyotesqrl** [comment]
build now

**Comment by bakejeyner** [comment]
Hero ✔️ 
- Create CSW sources and ensure they work correctly (✔️) 
- Create WFS 1.0, 1.1, and 2.0 sources and ensure they work correctly (❗️ [broken on master and release](https://codice.atlassian.net/browse/DDF-4255))
- Ensure security - CAS and XACML in particular - still work (✔️)
- Ensure that metacard transformations (ingests, etc.) still work correctly (✔️)

**Comment by oconnormi** [comment]
Job in jenkins hadn't been set up yet @coyotesqrl, should work now.

Build Now

**Comment by oconnormi** [comment]
My bad, missing a permission on sonarcloud

**Comment by oconnormi** [comment]
Build Now

**Pull request merged**
